name: weather
description: Test task.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.5
  get_it: 7.6.0
  injectable: 2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: 2.3.3
  flutter_lints: 2.0.2
  injectable_generator: 2.1.6

flutter:
  uses-material-design: true
